version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etx/nginx/conf.d
    depends_on:
      - app1
      - app2
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: curso
      POSTGRES_PASSWORD: ruku
      POSTGRES_DB: tingeso
    ports:
      - 5432:5432

  app1:
    container_name: proyecto_docker1
    image: falopino/pep1
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/tingeso
      - SPRING_DATASOURCE_USERNAME=curso
      - SPRING_DATASOURCE_PASSWORD=ruku
      - SERVER_PORT=8090
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db
  app2:
    container_name: proyecto_docker2
    image: falopino/pep1
    ports:
      - "8092:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/tingeso
      - SPRING_DATASOURCE_USERNAME=curso
      - SPRING_DATASOURCE_PASSWORD=ruku
      - SERVER_PORT=8090
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db
