server:
  port: 8090

spring:
  application:
    name: milkstgo
  jpa:
    show-sql: true
    hibernate:
      dialect: PostgreSQLDialect
      #ddl-auto: create
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    dbname: My_db
    url: jdbc:postgresql://localhost:5432/tingeso
    username: curso
    password: ruku

